//! Direct-equivalent tests for `src/native/re/parser.rs`.
//!
//! Expected ASTs were generated by running CPython's
//! `sre_parse.parse(pat)` on each input and hand-transcribing the result.
//! Every OP the parser can emit is exercised at least once.

use super::*;

fn parsed(pattern: &str) -> SubPattern {
    parse_pattern(pattern, 0)
        .unwrap_or_else(|e| panic!("parse {:?} failed: {}", pattern, e))
        .pattern
}

fn lit(cp: u32) -> OpCode {
    OpCode::Literal(cp)
}

#[test]
fn literal_single_char() {
    assert_eq!(parsed("a").data, vec![lit(97)]);
}

#[test]
fn literal_multi_char_concat() {
    assert_eq!(parsed("ab").data, vec![lit(97), lit(98)]);
}

#[test]
fn literal_escape() {
    // \n, \t, \\ produce literal code points.
    assert_eq!(parsed("\\n").data, vec![lit(10)]);
    assert_eq!(parsed("\\t").data, vec![lit(9)]);
    assert_eq!(parsed("\\\\").data, vec![lit(92)]);
}

#[test]
fn literal_hex_escape() {
    assert_eq!(parsed("\\x41").data, vec![lit(0x41)]);
}

#[test]
fn literal_unicode_u_escape() {
    assert_eq!(parsed("\\u00e9").data, vec![lit(0xe9)]);
}

#[test]
fn literal_octal_escape() {
    // \0 is octal zero.
    assert_eq!(parsed("\\0").data, vec![lit(0)]);
}

#[test]
fn any_dot() {
    assert_eq!(parsed(".").data, vec![OpCode::Any]);
}

#[test]
fn at_beginning_end() {
    assert_eq!(
        parsed("^abc$").data,
        vec![
            OpCode::At(AtCode::Beginning),
            lit(97),
            lit(98),
            lit(99),
            OpCode::At(AtCode::End),
        ]
    );
}

#[test]
fn at_beginning_end_string() {
    // \A and \Z
    assert_eq!(
        parsed("\\A\\Z").data,
        vec![
            OpCode::At(AtCode::BeginningString),
            OpCode::At(AtCode::EndString),
        ]
    );
}

#[test]
fn at_boundary() {
    // \b and \B are boundary assertions. With default flags they become UNI
    // boundary per fix_flags on a str pattern (though the base `AT` code is
    // what the parser emits).
    assert_eq!(
        parsed("\\b\\B").data,
        vec![
            OpCode::At(AtCode::Boundary),
            OpCode::At(AtCode::NonBoundary),
        ]
    );
}

#[test]
fn char_class_literal_set() {
    assert_eq!(
        parsed("[abc]").data,
        vec![OpCode::In(vec![
            SetItem::Literal(97),
            SetItem::Literal(98),
            SetItem::Literal(99),
        ])]
    );
}

#[test]
fn char_class_range() {
    assert_eq!(
        parsed("[a-z]").data,
        vec![OpCode::In(vec![SetItem::Range(97, 122)])]
    );
}

#[test]
fn char_class_negate() {
    assert_eq!(
        parsed("[^abc]").data,
        vec![OpCode::In(vec![
            SetItem::Negate,
            SetItem::Literal(97),
            SetItem::Literal(98),
            SetItem::Literal(99),
        ])]
    );
}

#[test]
fn char_class_mixed_ranges() {
    assert_eq!(
        parsed("[a-zA-Z0-9]").data,
        vec![OpCode::In(vec![
            SetItem::Range(97, 122),
            SetItem::Range(65, 90),
            SetItem::Range(48, 57),
        ])]
    );
}

#[test]
fn char_class_with_category() {
    assert_eq!(
        parsed("[\\d\\s]").data,
        vec![OpCode::In(vec![
            SetItem::Category(ChCode::Digit),
            SetItem::Category(ChCode::Space),
        ])]
    );
}

#[test]
fn char_class_leading_dash_literal() {
    // `-` at the start of a class is a literal.
    assert_eq!(
        parsed("[-abc]").data,
        vec![OpCode::In(vec![
            SetItem::Literal(45),
            SetItem::Literal(97),
            SetItem::Literal(98),
            SetItem::Literal(99),
        ])]
    );
}

#[test]
fn char_class_escaped_dash() {
    assert_eq!(
        parsed("[a\\-z]").data,
        vec![OpCode::In(vec![
            SetItem::Literal(97),
            SetItem::Literal(45),
            SetItem::Literal(122),
        ])]
    );
}

#[test]
fn char_class_closing_bracket_as_first_char() {
    // `[]]` matches a literal `]` (the first `]` is literal, the second closes).
    assert_eq!(parsed("[]]").data, vec![lit(93)]);
}

#[test]
fn char_class_single_literal_unwraps() {
    // `[a]` → LITERAL directly, not IN — the parser collapses a single-
    // element class.
    assert_eq!(parsed("[a]").data, vec![lit(97)]);
}

#[test]
fn char_class_single_literal_negated() {
    // `[^a]` → NOT_LITERAL.
    assert_eq!(parsed("[^a]").data, vec![OpCode::NotLiteral(97)]);
}

#[test]
fn digit_shortcut() {
    assert_eq!(
        parsed("\\d").data,
        vec![OpCode::In(vec![SetItem::Category(ChCode::Digit)])]
    );
}

#[test]
fn word_and_space_shortcuts() {
    assert_eq!(
        parsed("\\w").data,
        vec![OpCode::In(vec![SetItem::Category(ChCode::Word)])]
    );
    assert_eq!(
        parsed("\\s\\S").data,
        vec![
            OpCode::In(vec![SetItem::Category(ChCode::Space)]),
            OpCode::In(vec![SetItem::Category(ChCode::NotSpace)]),
        ]
    );
}

#[test]
fn max_repeat_plus() {
    assert_eq!(
        parsed("a+").data,
        vec![OpCode::MaxRepeat {
            min: 1,
            max: u32::MAX,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn max_repeat_star() {
    assert_eq!(
        parsed("a*").data,
        vec![OpCode::MaxRepeat {
            min: 0,
            max: u32::MAX,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn max_repeat_question() {
    assert_eq!(
        parsed("a?").data,
        vec![OpCode::MaxRepeat {
            min: 0,
            max: 1,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn max_repeat_braces_fixed() {
    assert_eq!(
        parsed("a{3}").data,
        vec![OpCode::MaxRepeat {
            min: 3,
            max: 3,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn max_repeat_braces_range() {
    assert_eq!(
        parsed("a{2,5}").data,
        vec![OpCode::MaxRepeat {
            min: 2,
            max: 5,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn max_repeat_braces_open_upper() {
    assert_eq!(
        parsed("a{3,}").data,
        vec![OpCode::MaxRepeat {
            min: 3,
            max: u32::MAX,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn max_repeat_braces_open_lower() {
    assert_eq!(
        parsed("a{,5}").data,
        vec![OpCode::MaxRepeat {
            min: 0,
            max: 5,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn min_repeat_plus_question() {
    assert_eq!(
        parsed("a+?").data,
        vec![OpCode::MinRepeat {
            min: 1,
            max: u32::MAX,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn possessive_repeat_double_plus() {
    assert_eq!(
        parsed("a++").data,
        vec![OpCode::PossessiveRepeat {
            min: 1,
            max: u32::MAX,
            item: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn repeat_overflow_is_error() {
    assert!(parse_pattern("a{4294967296}", 0).is_err());
}

#[test]
fn subpattern_capturing() {
    assert_eq!(
        parsed("(a)").data,
        vec![OpCode::Subpattern {
            group: Some(1),
            add_flags: 0,
            del_flags: 0,
            p: SubPattern { data: vec![lit(97)] },
        }]
    );
}

#[test]
fn subpattern_non_capturing_unwrapped() {
    // `(?:a)` has no flags and no group → the parser unwraps it in the
    // post-processing pass, leaving just the inner sequence.
    assert_eq!(parsed("(?:a)").data, vec![lit(97)]);
}

#[test]
fn subpattern_named_group() {
    // (?P<foo>a) opens group 1 named "foo".
    let parsed_full = parse_pattern("(?P<foo>a)", 0).unwrap();
    assert_eq!(
        parsed_full.pattern.data,
        vec![OpCode::Subpattern {
            group: Some(1),
            add_flags: 0,
            del_flags: 0,
            p: SubPattern { data: vec![lit(97)] },
        }]
    );
    assert_eq!(parsed_full.group_names.get("foo"), Some(&1));
    assert_eq!(parsed_full.group_count, 2);
}

#[test]
fn subpattern_inline_flags_scoped() {
    // (?i:abc) = SUBPATTERN(None, SRE_FLAG_IGNORECASE=2, 0, [a,b,c])
    assert_eq!(
        parsed("(?i:abc)").data,
        vec![OpCode::Subpattern {
            group: None,
            add_flags: 2,
            del_flags: 0,
            p: SubPattern {
                data: vec![lit(97), lit(98), lit(99)]
            },
        }]
    );
}

#[test]
fn subpattern_inline_flags_add_and_del() {
    // (?i-s:abc) → add IGNORECASE (2), del DOTALL (16)
    assert_eq!(
        parsed("(?i-s:abc)").data,
        vec![OpCode::Subpattern {
            group: None,
            add_flags: 2,
            del_flags: 16,
            p: SubPattern {
                data: vec![lit(97), lit(98), lit(99)]
            },
        }]
    );
}

#[test]
fn global_inline_flags() {
    // (?i)abc sets the global IGNORECASE flag and emits just the literals.
    let parsed_full = parse_pattern("(?i)abc", 0).unwrap();
    assert_eq!(
        parsed_full.pattern.data,
        vec![lit(97), lit(98), lit(99)]
    );
    assert!(parsed_full.flags & 2 != 0);
}

#[test]
fn groupref_decimal() {
    // (a)\1 → SUBPATTERN + GROUPREF 1.
    assert_eq!(
        parsed("(a)\\1").data,
        vec![
            OpCode::Subpattern {
                group: Some(1),
                add_flags: 0,
                del_flags: 0,
                p: SubPattern { data: vec![lit(97)] },
            },
            OpCode::GroupRef(1),
        ]
    );
}

#[test]
fn groupref_named() {
    assert_eq!(
        parsed("(?P<n>a)(?P=n)").data,
        vec![
            OpCode::Subpattern {
                group: Some(1),
                add_flags: 0,
                del_flags: 0,
                p: SubPattern { data: vec![lit(97)] },
            },
            OpCode::GroupRef(1),
        ]
    );
}

#[test]
fn groupref_invalid_is_error() {
    assert!(parse_pattern("a\\1", 0).is_err());
    assert!(parse_pattern("\\10", 0).is_err());
}

#[test]
fn groupref_exists() {
    assert_eq!(
        parsed("(a)(?(1)b|c)").data,
        vec![
            OpCode::Subpattern {
                group: Some(1),
                add_flags: 0,
                del_flags: 0,
                p: SubPattern { data: vec![lit(97)] },
            },
            OpCode::GroupRefExists {
                cond_group: 1,
                yes: SubPattern { data: vec![lit(98)] },
                no: Some(SubPattern { data: vec![lit(99)] }),
            },
        ]
    );
}

#[test]
fn assert_lookahead() {
    // (?=a)b
    assert_eq!(
        parsed("(?=a)b").data,
        vec![
            OpCode::Assert {
                direction: 1,
                p: SubPattern { data: vec![lit(97)] },
            },
            lit(98),
        ]
    );
}

#[test]
fn assert_not_lookahead() {
    assert_eq!(
        parsed("(?!a)b").data,
        vec![
            OpCode::AssertNot {
                direction: 1,
                p: SubPattern { data: vec![lit(97)] },
            },
            lit(98),
        ]
    );
}

#[test]
fn assert_lookbehind() {
    assert_eq!(
        parsed("(?<=a)b").data,
        vec![
            OpCode::Assert {
                direction: -1,
                p: SubPattern { data: vec![lit(97)] },
            },
            lit(98),
        ]
    );
}

#[test]
fn assert_not_lookbehind() {
    assert_eq!(
        parsed("(?<!a)b").data,
        vec![
            OpCode::AssertNot {
                direction: -1,
                p: SubPattern { data: vec![lit(97)] },
            },
            lit(98),
        ]
    );
}

#[test]
fn atomic_group() {
    assert_eq!(
        parsed("(?>a)").data,
        vec![OpCode::AtomicGroup(SubPattern { data: vec![lit(97)] })]
    );
}

#[test]
fn branch_three_way() {
    // ab|cd|ef does not have a common prefix or single-literal collapse,
    // so it stays as BRANCH.
    assert_eq!(
        parsed("ab|cd|ef").data,
        vec![OpCode::Branch(vec![
            SubPattern { data: vec![lit(97), lit(98)] },
            SubPattern { data: vec![lit(99), lit(100)] },
            SubPattern { data: vec![lit(101), lit(102)] },
        ])]
    );
}

#[test]
fn branch_single_letters_collapse_to_set() {
    // a|b|c → IN([a, b, c]) by the parser's set-collapse optimization.
    assert_eq!(
        parsed("a|b|c").data,
        vec![OpCode::In(vec![
            SetItem::Literal(97),
            SetItem::Literal(98),
            SetItem::Literal(99),
        ])]
    );
}

#[test]
fn branch_shared_prefix_moved_out() {
    // abc|abd → [a, b, IN([c, d])] via prefix extraction + set collapse.
    assert_eq!(
        parsed("abc|abd").data,
        vec![
            lit(97),
            lit(98),
            OpCode::In(vec![
                SetItem::Literal(99),
                SetItem::Literal(100),
            ]),
        ]
    );
}

#[test]
fn comment_is_discarded() {
    // (?#...) comments contribute nothing to the output.
    assert_eq!(parsed("a(?#comment)b").data, vec![lit(97), lit(98)]);
}

#[test]
fn named_unicode_escape_errors() {
    // \N{...} is not yet supported — the parser should return an error
    // rather than silently mis-parsing.
    assert!(parse_pattern(r"\N{LATIN SMALL LETTER A}", 0).is_err());
}

#[test]
fn full_complex_pattern() {
    // Non-trivial sanity check: a reasonable URL-ish pattern parses
    // without error and reports the expected group count.
    let p = parse_pattern(r"https?://(?P<host>[\w.-]+)(:\d+)?(/\S*)?", 0).unwrap();
    assert_eq!(p.group_count, 4);
    assert_eq!(p.group_names.get("host"), Some(&1));
}
