//! Port of `hypothesis.internal.conjecture.utils`: small helpers shared
//! across the engine, exposed for tests via `__native_test_internals`.
//!
//! Covers `_calc_p_continue`, `_p_continue_to_avg`, `SMALLEST_POSITIVE_FLOAT`,
//! `Sampler` (Vose's alias method), `Many` (variable-length collection helper),
//! and `combine_labels`.

use std::cmp::Reverse;
use std::collections::BinaryHeap;

use crate::native::core::{NativeTestCase, Status, StopTest};

/// Smallest positive `f64`. Mirrors Hypothesis's `cu.SMALLEST_POSITIVE_FLOAT`,
/// which is `next_up(0.0)` (the smallest positive subnormal).
pub const SMALLEST_POSITIVE_FLOAT: f64 = f64::from_bits(1);

/// Return the average size generated by this `p_continue` and `max_size`.
///
/// Port of `hypothesis.internal.conjecture.utils._p_continue_to_avg`.
pub fn p_continue_to_avg(p_continue: f64, max_size: f64) -> f64 {
    if p_continue >= 1.0 {
        return max_size;
    }
    (1.0 / (1.0 - p_continue) - 1.0) * (1.0 - p_continue.powf(max_size))
}

/// Return the `p_continue` which will generate the desired average size.
///
/// Port of `hypothesis.internal.conjecture.utils._calc_p_continue`.
pub fn calc_p_continue(desired_avg: f64, max_size: f64) -> f64 {
    assert!(
        desired_avg <= max_size,
        "desired_avg {desired_avg} > max_size {max_size}"
    );
    if desired_avg == max_size {
        return 1.0;
    }
    let mut p_continue = 1.0 - 1.0 / (1.0 + desired_avg);
    if p_continue == 0.0 || max_size.is_infinite() {
        assert!((0.0..1.0).contains(&p_continue));
        return p_continue;
    }
    assert!(0.0 < p_continue && p_continue < 1.0);
    while p_continue_to_avg(p_continue, max_size) > desired_avg {
        p_continue -= 0.0001;
        if p_continue < SMALLEST_POSITIVE_FLOAT {
            p_continue = SMALLEST_POSITIVE_FLOAT;
            break;
        }
    }
    let mut hi = 1.0;
    while desired_avg - p_continue_to_avg(p_continue, max_size) > 0.01 {
        assert!(0.0 < p_continue && p_continue < hi);
        let mid = (p_continue + hi) / 2.0;
        if p_continue_to_avg(mid, max_size) <= desired_avg {
            p_continue = mid;
        } else {
            hi = mid;
        }
    }
    assert!(0.0 < p_continue && p_continue < 1.0);
    assert!(p_continue_to_avg(p_continue, max_size) <= desired_avg);
    p_continue
}

/// Build the Vose alias-method table for `weights`.
///
/// Port of `hypothesis.internal.conjecture.utils.compute_sampler_table`.
/// Returns triples `(base, alternate, alternate_chance)` sorted
/// lexicographically, with the invariant `base <= alternate` so that
/// shrinking the sampler's index choice always shrinks the chosen element.
pub(crate) fn compute_sampler_table(weights: &[f64]) -> Vec<(usize, usize, f64)> {
    let n = weights.len();
    let total: f64 = weights.iter().sum();

    let mut alternates: Vec<Option<usize>> = vec![None; n];
    let mut alt_chances: Vec<Option<f64>> = vec![None; n];

    let mut small: BinaryHeap<Reverse<usize>> = BinaryHeap::new();
    let mut large: BinaryHeap<Reverse<usize>> = BinaryHeap::new();

    let mut scaled_probabilities: Vec<f64> = Vec::with_capacity(n);
    for (i, &w) in weights.iter().enumerate() {
        let scaled = (w / total) * (n as f64);
        scaled_probabilities.push(scaled);
        if scaled == 1.0 {
            alt_chances[i] = Some(0.0);
        } else if scaled < 1.0 {
            small.push(Reverse(i));
        } else {
            large.push(Reverse(i));
        }
    }

    while !small.is_empty() && !large.is_empty() {
        let Reverse(lo) = small.pop().unwrap();
        let Reverse(hi) = large.pop().unwrap();

        assert!(lo != hi);
        assert!(scaled_probabilities[hi] > 1.0);
        assert!(alternates[lo].is_none());
        alternates[lo] = Some(hi);
        alt_chances[lo] = Some(1.0 - scaled_probabilities[lo]);
        scaled_probabilities[hi] = (scaled_probabilities[hi] + scaled_probabilities[lo]) - 1.0;

        if scaled_probabilities[hi] < 1.0 {
            small.push(Reverse(hi));
        } else if scaled_probabilities[hi] == 1.0 {
            alt_chances[hi] = Some(0.0);
        } else {
            large.push(Reverse(hi));
        }
    }
    while let Some(Reverse(i)) = large.pop() {
        alt_chances[i] = Some(0.0);
    }
    while let Some(Reverse(i)) = small.pop() {
        alt_chances[i] = Some(0.0);
    }

    let mut new_table: Vec<(usize, usize, f64)> = Vec::with_capacity(n);
    for base in 0..n {
        let alternate_chance = alt_chances[base].expect("alternate_chance was set above");
        match alternates[base] {
            None => new_table.push((base, base, alternate_chance)),
            Some(alternate) if alternate < base => {
                new_table.push((alternate, base, 1.0 - alternate_chance));
            }
            Some(alternate) => new_table.push((base, alternate, alternate_chance)),
        }
    }
    new_table.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)).then(a.2.total_cmp(&b.2)));
    new_table
}

/// Sampler based on Vose's alias method.
///
/// Port of `hypothesis.internal.conjecture.utils.Sampler`. We store a table
/// of triples `(base, alternate, alternate_chance)`. To draw, pick a triple
/// uniformly and choose its `alternate` value with probability
/// `alternate_chance` (else `base`); the table is constructed so the
/// resulting mixture matches the input weight distribution.
pub struct Sampler {
    /// Vose alias-method table: `(base, alternate, alternate_chance)`.
    pub table: Vec<(usize, usize, f64)>,
}

impl Sampler {
    /// Build a sampler from a sequence of non-negative weights.
    pub fn new(weights: &[f64]) -> Self {
        Sampler {
            table: compute_sampler_table(weights),
        }
    }

    /// Draw a sample. Returns an index in `0..weights.len()`.
    ///
    /// Mirrors `Sampler.sample` in Hypothesis: uniformly pick a table entry,
    /// then with probability `alternate_chance` return `alternate`, else
    /// return `base`. Pass `forced=Some(v)` to force a specific result value.
    pub fn sample(
        &self,
        data: &mut NativeTestCase,
        forced: Option<usize>,
    ) -> Result<usize, StopTest> {
        let n = self.table.len();
        let (forced_idx, forced_use_alternate) = if let Some(fv) = forced {
            let (entry_idx, entry) = self
                .table
                .iter()
                .enumerate()
                .find(|&(_, &(b, a, p))| fv == b || (fv == a && p > 0.0))
                .expect("forced value not in sampler table");
            let (_base, alternate, alt_chance) = *entry;
            let use_alt = fv == alternate && alt_chance > 0.0;
            (Some(entry_idx as i128), Some(use_alt))
        } else {
            (None, None)
        };

        let idx = if let Some(fi) = forced_idx {
            data.draw_integer_forced(0, (n - 1) as i128, fi)? as usize
        } else {
            data.draw_integer(0, (n - 1) as i128)? as usize
        };
        let (base, alternate, alternate_chance) = self.table[idx];
        let use_alternate = data.weighted(alternate_chance, forced_use_alternate)?;
        Ok(if use_alternate { alternate } else { base })
    }
}

/// Combine multiple span labels into one. Port of `hypothesis.internal.conjecture.utils.combine_labels`.
///
/// Applies `label = (label << 1) & u64::MAX ^ l` for each input label, starting from 0.
/// A single-argument call is an identity: `combine_labels(&[n]) == n`.
pub fn combine_labels(labels: &[u64]) -> u64 {
    let mut label: u64 = 0;
    for &l in labels {
        label = label.wrapping_shl(1);
        label ^= l;
    }
    label
}

/// Variable-length collection helper. Port of `hypothesis.internal.conjecture.utils.Many`.
///
/// Tracks how many elements should be drawn for a collection, stopping based on
/// a geometric distribution with probability `p_continue` derived from `average_size`.
pub struct Many {
    pub min_size: usize,
    pub max_size: f64,
    pub p_continue: f64,
    pub count: usize,
    pub rejections: usize,
    pub force_stop: bool,
}

impl Many {
    /// Build a `Many` from explicit `min_size`, `max_size`, and `average_size`.
    ///
    /// Mirrors `cu.many(data, min_size, max_size, average_size)` in Hypothesis.
    pub fn new(min_size: usize, max_size: f64, average_size: f64) -> Self {
        let min_f = min_size as f64;
        let desired_extra = average_size - min_f;
        let max_extra = max_size - min_f;
        let p_continue = if desired_extra == max_extra {
            1.0
        } else if max_extra == 0.0 || desired_extra <= 0.0 {
            calc_p_continue(desired_extra.max(0.0), max_extra.max(0.0))
        } else {
            calc_p_continue(desired_extra, max_extra)
        };
        Many {
            min_size,
            max_size,
            p_continue,
            count: 0,
            rejections: 0,
            force_stop: false,
        }
    }

    /// Should another element be drawn? Mirrors `Many.more()` in Hypothesis.
    pub fn more(&mut self, data: &mut NativeTestCase) -> Result<bool, StopTest> {
        let should_continue = if self.min_size as f64 == self.max_size {
            self.count < self.min_size
        } else {
            let forced = if self.force_stop {
                Some(false)
            } else if self.count < self.min_size {
                Some(true)
            } else if self.count as f64 >= self.max_size {
                Some(false)
            } else {
                None
            };
            data.weighted(self.p_continue, forced)?
        };
        if should_continue {
            self.count += 1;
        }
        Ok(should_continue)
    }

    /// Reject the last drawn element. Mirrors `Many.reject()` in Hypothesis.
    pub fn reject(&mut self, data: &mut NativeTestCase) -> Result<(), StopTest> {
        assert!(self.count > 0);
        self.count -= 1;
        self.rejections += 1;
        if self.rejections > std::cmp::max(3, 2 * self.count) {
            if self.count < self.min_size {
                data.status = Some(Status::Invalid);
                return Err(StopTest);
            } else {
                self.force_stop = true;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
#[path = "../../tests/embedded/native/conjecture_utils_tests.rs"]
mod tests;
