//! Port of `hypothesis.internal.conjecture.utils`: small helpers shared
//! across the engine, exposed for tests via `__native_test_internals`.
//!
//! Currently covers `_calc_p_continue`, `_p_continue_to_avg`, and
//! `SMALLEST_POSITIVE_FLOAT`. `Sampler` (Vose's alias method) is stubbed —
//! the existing native engine doesn't use it on a hot path, but the
//! upstream `nocover/test_conjecture_utils.py` covers it, so it's wired in
//! pending an implementation pass.

use crate::native::core::{NativeTestCase, StopTest};

/// Smallest positive `f64`. Mirrors Hypothesis's `cu.SMALLEST_POSITIVE_FLOAT`,
/// which is `next_up(0.0)` (the smallest positive subnormal).
pub const SMALLEST_POSITIVE_FLOAT: f64 = f64::from_bits(1);

/// Return the average size generated by this `p_continue` and `max_size`.
///
/// Port of `hypothesis.internal.conjecture.utils._p_continue_to_avg`.
pub fn p_continue_to_avg(p_continue: f64, max_size: f64) -> f64 {
    if p_continue >= 1.0 {
        return max_size;
    }
    (1.0 / (1.0 - p_continue) - 1.0) * (1.0 - p_continue.powf(max_size))
}

/// Return the `p_continue` which will generate the desired average size.
///
/// Port of `hypothesis.internal.conjecture.utils._calc_p_continue`.
pub fn calc_p_continue(desired_avg: f64, max_size: f64) -> f64 {
    assert!(
        desired_avg <= max_size,
        "desired_avg {desired_avg} > max_size {max_size}"
    );
    if desired_avg == max_size {
        return 1.0;
    }
    let mut p_continue = 1.0 - 1.0 / (1.0 + desired_avg);
    if p_continue == 0.0 || max_size.is_infinite() {
        assert!((0.0..1.0).contains(&p_continue));
        return p_continue;
    }
    assert!(0.0 < p_continue && p_continue < 1.0);
    while p_continue_to_avg(p_continue, max_size) > desired_avg {
        p_continue -= 0.0001;
        if p_continue < SMALLEST_POSITIVE_FLOAT {
            p_continue = SMALLEST_POSITIVE_FLOAT;
            break;
        }
    }
    let mut hi = 1.0;
    while desired_avg - p_continue_to_avg(p_continue, max_size) > 0.01 {
        assert!(0.0 < p_continue && p_continue < hi);
        let mid = (p_continue + hi) / 2.0;
        if p_continue_to_avg(mid, max_size) <= desired_avg {
            p_continue = mid;
        } else {
            hi = mid;
        }
    }
    assert!(0.0 < p_continue && p_continue < 1.0);
    assert!(p_continue_to_avg(p_continue, max_size) <= desired_avg);
    p_continue
}

/// Sampler based on Vose's alias method. Port of `cu.Sampler`.
///
/// The general idea is that we store a table of triples
/// `(base, alternate, alternate_chance)`. Picking a triple uniformly at
/// random and then choosing its `alternate` value with probability
/// `alternate_chance` (else the `base`) reproduces the input distribution.
///
/// The alias-method table construction (`compute_sampler_table`) and
/// `sample` are not yet ported; the constructor stores raw weights so
/// callers can hold a `Sampler` while we wait for the implementation.
pub struct Sampler {
    pub weights: Vec<f64>,
}

impl Sampler {
    /// Build a sampler from a sequence of non-negative weights.
    pub fn new(weights: &[f64]) -> Self {
        Sampler {
            weights: weights.to_vec(),
        }
    }

    /// Draw a sample. Returns an index in `0..weights.len()`.
    pub fn sample(&self, _data: &mut NativeTestCase) -> Result<usize, StopTest> {
        todo!(
            "port hypothesis.internal.conjecture.utils.Sampler.sample: build the \
             Vose alias-method table from self.weights (compute_sampler_table), \
             then pick a triple via data.draw_integer and data.weighted on \
             alternate_chance to choose between base and alternate"
        );
    }
}
