#!/usr/bin/env python3
"""Generate src/native/unicodedata/tables.rs from UnicodeData.txt.

Run from the repo root:

    python scripts/generate_unicodedata_tables.py

Reads `src/native/unicodedata/UnicodeData.txt` (vendored from
https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt) and emits a
run-length-encoded lookup table as Rust source. Codepoints not listed
in UnicodeData.txt are treated as `Cn` (Unassigned), matching Python's
`unicodedata.category`.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
UCD_PATH = REPO_ROOT / "src" / "native" / "unicodedata" / "UnicodeData.txt"
OUT_PATH = REPO_ROOT / "src" / "native" / "unicodedata" / "tables.rs"

# Categories in the same order as the Rust enum. Keeping them in a stable
# order means the generated file only churns when the underlying data
# changes.
CATEGORIES = [
    "Lu", "Ll", "Lt", "Lm", "Lo",
    "Mn", "Mc", "Me",
    "Nd", "Nl", "No",
    "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
    "Sm", "Sc", "Sk", "So",
    "Zs", "Zl", "Zp",
    "Cc", "Cf", "Cs", "Co", "Cn",
]

MAX_CP = 0x10FFFF


def parse_unicode_data(path: Path) -> dict[int, str]:
    """Parse UnicodeData.txt into {codepoint: category}.

    Expands the "<..., First>" / "<..., Last>" range markers.
    """
    entries: dict[int, str] = {}
    lines = [l for l in path.read_text().splitlines() if l]
    i = 0
    while i < len(lines):
        fields = lines[i].split(";")
        cp = int(fields[0], 16)
        name = fields[1]
        cat = fields[2]
        if name.endswith(", First>"):
            i += 1
            fields2 = lines[i].split(";")
            cp_end = int(fields2[0], 16)
            assert fields2[1].endswith(", Last>"), fields2
            for c in range(cp, cp_end + 1):
                entries[c] = cat
        else:
            entries[cp] = cat
        i += 1
    return entries


def build_ranges(entries: dict[int, str]) -> list[tuple[int, int, str]]:
    """Collapse per-codepoint categories into contiguous runs.

    Codepoints not in `entries` default to `Cn`.
    """
    ranges: list[tuple[int, int, str]] = []
    current_cat: str | None = None
    current_start = 0
    for cp in range(MAX_CP + 1):
        cat = entries.get(cp, "Cn")
        if cat != current_cat:
            if current_cat is not None:
                ranges.append((current_start, cp - 1, current_cat))
            current_cat = cat
            current_start = cp
    assert current_cat is not None
    ranges.append((current_start, MAX_CP, current_cat))
    return ranges


def emit(ranges: list[tuple[int, int, str]], out_path: Path) -> None:
    seen_cats = sorted({r[2] for r in ranges})
    unknown = [c for c in seen_cats if c not in CATEGORIES]
    if unknown:
        sys.exit(f"Unknown categories in UnicodeData.txt: {unknown}")

    lines = [
        "// Auto-generated by scripts/generate_unicodedata_tables.py.",
        "// Do not edit by hand; regenerate if UnicodeData.txt changes.",
        "",
        "use super::Category;",
        "",
        "/// Run-length-encoded General Category table, covering all codepoints",
        "/// in `0..=0x10FFFF`. Entries are non-overlapping, contiguous, and",
        "/// sorted by `end`. Lookup = binary search for the first entry with",
        "/// `end >= cp`.",
        f"pub(super) const RANGES: &[(u32, Category)] = &[",
    ]
    for _, end, cat in ranges:
        lines.append(f"    ({end:#07x}, Category::{cat}),")
    lines.append("];")
    lines.append("")

    out_path.write_text("\n".join(lines))


def main() -> None:
    entries = parse_unicode_data(UCD_PATH)
    ranges = build_ranges(entries)
    emit(ranges, OUT_PATH)
    print(f"Wrote {OUT_PATH} with {len(ranges)} ranges.")


if __name__ == "__main__":
    main()
