//! Ported from hypothesis-python/tests/nocover/test_explore_arbitrary_languages.py
//!
//! Drives a `NativeConjectureRunner` with arbitrary "language" trees
//! (Write / Branch / Terminal nodes) generated by an outer `Hegel::new(...)`
//! test, fuzzing the engine's behaviour across diverse choice-graph shapes.
//!
//! Only `test_explore_an_arbitrary_language` ports.  The upstream
//! `test_run_specific_example` is parametrised with an empty list of rows
//! and never fires; we omit it.
//!
//! The Python original disables shrinking on the outer test
//! (`phases=set(default) - {Phase.shrink}`).  hegel-rust's public `Settings`
//! has no `phases()` knob, so the outer test runs with default phases —
//! the tested behaviour (the inner `NativeConjectureRunner` not crashing on
//! arbitrary languages) is unchanged; only outer-level shrink-on-failure
//! cost differs.

#![cfg(feature = "native")]

use hegel::__native_test_internals::{
    HealthCheckLabel, NativeConjectureData, NativeConjectureRunner, NativeRunnerSettings,
    interesting_origin,
};
use hegel::generators::{self as gs, BoxedGenerator, Generator};
use hegel::{HealthCheck, Hegel, Settings, TestCase};
use rand::SeedableRng;
use rand::rngs::SmallRng;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

#[derive(Debug, Clone)]
enum Status {
    Valid,
    Invalid,
    Interesting(i64),
}

// `children` uses `Arc<Mutex<...>>` rather than `Rc<RefCell<...>>` because
// `JustGenerator<T>` and `BoxedGenerator<T>` require `T: Send + Sync`, which
// pulls a `Send + Sync` bound onto `Node` even though every test runs on a
// single thread.  The Python original mutates the dict in place with no
// locking; the `Mutex` here is essentially uncontended and just satisfies
// the trait bounds.
#[derive(Debug, Clone)]
enum Node {
    Terminal(Status),
    Branch {
        bits: u32,
        children: Arc<Mutex<HashMap<i128, Node>>>,
    },
    Write {
        value: Vec<u8>,
        child: Box<Node>,
    },
}

fn build_generators() -> (BoxedGenerator<'static, Node>, BoxedGenerator<'static, Node>) {
    let nodes_def = gs::deferred::<Node>();
    let nodes_handle = nodes_def.generator();

    let valid = gs::just(Node::Terminal(Status::Valid));
    let invalid = gs::just(Node::Terminal(Status::Invalid));
    let interesting = gs::integers::<i64>()
        .min_value(0)
        .max_value(10)
        .map(|p| Node::Terminal(Status::Interesting(p)))
        .boxed();
    let terminals: BoxedGenerator<'static, Node> =
        hegel::one_of!(valid, invalid, interesting).boxed();

    let branches: BoxedGenerator<'static, Node> = gs::integers::<u32>()
        .min_value(1)
        .max_value(64)
        .map(|bits| Node::Branch {
            bits,
            children: Arc::new(Mutex::new(HashMap::new())),
        })
        .boxed();

    let writes: BoxedGenerator<'static, Node> =
        hegel::tuples!(gs::binary().min_size(1), nodes_handle.clone())
            .map(|(value, child): (Vec<u8>, Node)| Node::Write {
                value,
                child: Box::new(child),
            })
            .boxed();

    nodes_def.set(hegel::one_of!(
        terminals,
        writes.clone(),
        branches.clone()
    ));

    let writes_or_branches: BoxedGenerator<'static, Node> =
        hegel::one_of!(writes, branches).boxed();
    (nodes_handle, writes_or_branches)
}

#[test]
fn test_explore_an_arbitrary_language() {
    let (nodes_handle, writes_or_branches) = build_generators();

    Hegel::new(move |tc: TestCase| {
        let root: Node = tc.draw(writes_or_branches.clone());
        let seed: u64 = tc.draw(gs::integers::<u64>());
        let outer_tc = tc.clone();
        let nodes_handle_inner = nodes_handle.clone();
        let root_for_inner = root.clone();

        let test_fn = move |local_data: &mut NativeConjectureData| {
            let mut node = root_for_inner.clone();
            loop {
                let next = match node {
                    Node::Terminal(Status::Valid) => return,
                    Node::Terminal(Status::Invalid) => local_data.mark_invalid(),
                    Node::Terminal(Status::Interesting(p)) => {
                        local_data.mark_interesting(interesting_origin(Some(p)))
                    }
                    Node::Write { value, child } => {
                        let len = value.len();
                        local_data.draw_bytes_forced(len, len, value);
                        *child
                    }
                    Node::Branch { bits, children } => {
                        let max = (1i128 << bits) - 1;
                        let c = local_data.draw_integer(0, max);
                        let mut guard = children.lock().unwrap();
                        if let Some(existing) = guard.get(&c) {
                            existing.clone()
                        } else {
                            let new_child: Node = outer_tc.draw(nodes_handle_inner.clone());
                            guard.insert(c, new_child.clone());
                            new_child
                        }
                    }
                };
                node = next;
            }
        };

        let rng = SmallRng::seed_from_u64(seed);
        let settings = NativeRunnerSettings::new()
            .max_examples(1)
            .suppress_health_check(vec![
                HealthCheckLabel::FilterTooMuch,
                HealthCheckLabel::TooSlow,
                HealthCheckLabel::LargeBaseExample,
                HealthCheckLabel::DataTooLarge,
            ]);
        let mut runner = NativeConjectureRunner::new(test_fn, settings, rng);
        runner.run();
        tc.note(&format!("{:?}", root));
        tc.assume(!runner.interesting_examples.is_empty());
    })
    .settings(
        Settings::new()
            .database(None)
            // The Python original runs the default 100 outer cases, but each
            // case in hegel-rust is dominated by inner-runner shrinking on
            // deeply-recursive language trees and the upstream test is in
            // `nocover/` for the same reason — slow by nature. Trim the
            // outer batch to fit hegel-rust's per-test budget; 20 still
            // exercises plenty of distinct languages per run.
            .test_cases(20)
            .suppress_health_check(HealthCheck::all()),
    )
    .run();
}
