name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions: {}

jobs:
  check-release:
    name: check release
    if: "!contains(github.event.pull_request.labels.*.name, 'skip release')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@ad397744b0d591a723ab90405b7247fac0e6b8db # v2

      - name: Install cargo-semver-checks
        run: cargo install --locked cargo-semver-checks

      - name: Check release
        env:
          BASE_REF: ${{ github.base_ref }}
        run: python .github/scripts/release.py check "$BASE_REF"
